- name: ansible data type
  hosts: local
  connection: local
  vars:
    DURATION: 120 # this is number
    COURSE: "DevSecOps with AWS" # string
    IS_LIVE: true #boolean
    Tools: # if it starts with - is a list in yaml
    - Linux
    - shell
    - Ansible
    CONCEPTS:  # map or dictionary or object. refered like {}
      CI: Jenkis
      SCRIPTING: "Shell, Ansible, Terraform, Python"
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: " Course is: {{ COURSE }}, Duration: {{ DURATION }}, is Live?: {{ IS_LIVE }}, Tools are: {{ Tools }}, Concepts are: {{ CONCEPTS }}"
