- name: functions
  hosts: local
  connection: local
  vars: 
    persons: "ramesh,suresh,raheem,joseph"

  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ person | default ('Ramesh') }}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ persons | split (',') }}"

  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10HR
        trainer: Siva
    ansible.builtin.debug:
      msg: "Course Infor: {{ course | dict2items }}"

  - name: convert list into map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10HR'}
      - {'key': 'trainer', 'value': 'sivakumar'}

    ansible.builtin.debug:
      msg: "Course Infor: {{ course | items2dict }}"
    
